// Client-safe keys (RLS enforced). Regenerated by `npm run build` when using CI env vars.
window.SUPABASE_URL = "https://iyupqbranxgwjhickaui.supabase.co";
window.SUPABASE_ANON_KEY =
  "sb_publishable_MQ8n0LiP03DUvQJaA4L-vQ_FqDcvOJR";
